name: ci
on:
  workflow_dispatch: {}
  push:
    branches:
      - main-bc
    tags:
      - v*
  pull_request:
    branches:
      - main-bc
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build-docker-image:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
          cache: false

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to harbor.onebrief.tools
        uses: docker/login-action@v2
        with:
          registry: harbor.onebrief.tools
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::183613197217:role/GitHubAction-AssumeRoleWithAction-ECR-ReadOnly
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/onebrief/gotenberg
            harbor.onebrief.tools/onebrief/gotenberg
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Docker Build
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./build/Dockerfile.bc
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64

      - name: Test conversions
        id: tests
        uses: addnab/docker-run-action@v3
        with:
          image:  harbor.onebrief.tools/onebrief/gotenberg@${{ steps.build.outputs.imageid }}
          options: -v ${{ github.workspace }}:/tmp
          run: |
            wget --method=POST \
              --header="Content-Type: multipart/form-data" \
              --body-file=/tmp/.github/testFiles/sample.docx \
              -O outputFiles/sample-docx.pdf \
              http://localhost:3000/forms/libreoffice/convert

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        continue-on-error: true
        with:
          image-ref: harbor.onebrief.tools/onebrief/gotenberg@${{ steps.build.outputs.imageid }}
          scanners: "vuln"
          format: "table"
        env:
          TRIVY_USERNAME: ${{ secrets.HARBOR_RO_USER }}
          TRIVY_PASSWORD: ${{ secrets.HARBOR_RO_TOKEN }}
